### ISSUE TITLE
Steps forward

### ISSUE THREAD

**Issue by chessai** [chessai/silvi#5]
Expose Parsers
Better Show instances for Record types (clunky and useless as of now)
Support IPv6 (Simple to do)

**Comment by chessai** [comment]
@andrewthad, should I defined a newtype wrapper around Rec, called Log, that has the Show and ShowForall instances that I want? Or is there a better way of doing this?

**Comment by andrewthad** [comment]
If you want it as a `Show` instance, then that's the best way to go about it. However, what I typically do in would just be to write a function named something like `pretty`, `encode`, or `visualize`:

    encode :: Rec Field rs -> String    

You could even use `Text` instead of `String` depending on the context in which you actually expect this to be used.

**Comment by chessai** [comment]
I made this into 3 different issues.
